POST https://issue-tracker.freecodecamp.rocks/api/issues/gabo HTTP/1.1
Content-Type: application/json

{
    "issue_title": "t",
    "issue_text": "t",
    "created_by": "t",
    "assigned_to": "",
    "status_text": "",
    "project": "gabo"
}

###
POST http://localhost:3000/api/issues/apitest HTTP/1.1
Content-Type: application/json

{
    "issue_title": "",
    "issue_text": "",
    "created_by": "",
    "assigned_to": "",
    "status_text": "",
    "project": "apitest"
}

###
POST https://boilerplate-project-issuetracker.onrender.com/api/issues/apitest HTTP/1.1
Content-Type: application/json

{
    "issue_title": "",
    "issue_text": "",
    "created_by": "",
    "assigned_to": "",
    "status_text": "",
    "project": "apitest"
}

###
GET http://localhost:3000/api/issues/apitest HTTP/1.1

###
PUT https://issue-tracker.freecodecamp.rocks/api/issues/gabo HTTP/1.1
Content-Type: application/json

{
}

###
PUT http://localhost:3000/api/issues/gabo HTTP/1.1
Content-Type: application/json

{
    "_id": "6469253234fee16839b85f59",
    "issue_title": "mmmmmmmmmmmmm"
    
}

###
PUT http://localhost:3000/api/issues/gabo HTTP/1.1
Content-Type: application/json

{
    "_id": "9834298",
    "issue_title": "mmmmmmmmmmmmm"
}

###
PUT https://issue-tracker.freecodecamp.rocks/api/issues/gabo HTTP/1.1
Content-Type: application/json

{
}

###
DELETE https://issue-tracker.freecodecamp.rocks/api/issues/gabo HTTP/1.1
Content-Type: application/json

{
    "_id": "646d8368af52fd3d74d7ba12"
}

###
DELETE http://localhost:3000/api/issues/gabo HTTP/1.1
Content-Type: application/json

{
    "_id": ""
}
