POST https://issue-tracker.freecodecamp.rocks/api/issues/gabo HTTP/1.1
Content-Type: application/json

{
    "issue_title": "t",
    "issue_text": "t",
    "created_by": "",
    "assigned_to": "",
    "status_text": "",
    "project": "gabo"
}

###
POST http://localhost:3000/api/issues/apitest HTTP/1.1
Content-Type: application/json

{
    "issue_title": "great",
    "issue_text": "great",
    "created_by": "great",
    "assigned_to": "",
    "status_text": "",
    "project": "apitest"
}

###
GET http://localhost:3000/api/issues/apitest HTTP/1.1

###
PUT https://issue-tracker.freecodecamp.rocks/api/issues/gabo HTTP/1.1
Content-Type: application/json

{
    "_id": "646be42e58b24e02d0aa4d96"
}

###
PUT http://localhost:3000/api/issues/gabo HTTP/1.1
Content-Type: application/json

{
    "_id": "6469253234fee16839b85f59",
    "issue_title": "mmmmmmmmmmmmm"
    
}

###
PUT http://localhost:3000/api/issues/gabo HTTP/1.1
Content-Type: application/json

{
    "_id": "64691c71cbe69ade23c8e847" 
}

###
PUT https://issue-tracker.freecodecamp.rocks/api/issues/gabo HTTP/1.1
Content-Type: application/json

{
}